### ISSUE TITLE
When Update XXX Where Clause Problem

### ISSUE THREAD

**Issue by volkankorkmaz** [manikandanraji/twitter-clone-backend#1]
Hi,

I tried to update my company table but where clause is missing.

How can I set up the company.graphql file?

Thank you

File Content as below:
type Mutation {
  updateCompany(       
    id: ID! 
    name: String!
    address1: String
    address2: String
  ): Company!
}

**Comment by manikandanraji** [comment]
You can refer this `https://github.com/manikandanraji/twitter-clone-backend/tree/master/src/api/Tweet/updateTweet`.

**Comment by volkankorkmaz** [comment]
> You can refer this [updateTweet](https://github.com/manikandanraji/twitter-clone-backend/tree/master/src/api/Tweet/updateTweet)

Thanks ;)
